version: '3.8'

services:
  app:
    image: node:18-alpine
    working_dir: /app
    command: |
      sh -c "
        apk add --no-cache git postgresql-client &&
        git clone https://github.com/YOUR_USERNAME/smartline-backend.git . &&
        npm install &&
        npx prisma generate &&
        npx prisma migrate deploy &&
        node src/index.js
      "
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
    restart: unless-stopped