  name: Deploy to Ubuntu Server

  on:
    push:
      branches: [ main, master ]
    workflow_dispatch:

  jobs:
    deploy:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/smartline-api/SmartLineAI
            git pull origin main
            npm install
            npx prisma generate
            npx prisma migrate deploy
            pm2 restart smartline-api
            pm2 save
            echo "Deployment completed successfully"
  EOF

